=== EdgarRafaelRomeroMartin/DTD/src/test/Liga.dtd
<!ELEMENT Liga (Partido)*>
        <!ELEMENT Partido (equipos)*>
        <!ELEMENT equipos (NombreEquipo,Puntuacion,estadisticas)*>
        <!ATTLIST equipos
                tipo CDATA #REQUIRED>
        <!ELEMENT NombreEquipo (#PCDATA)>
        <!ELEMENT Puntuacion (#PCDATA)>
        <!ELEMENT estadisticas (#PCDATA)>

=== EdgarRafaelRomeroMartin/DTD/src/test/LigaBBVA.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE Liga SYSTEM "Liga.dtd">
<Liga>
<Partido>
  <equipos tipo="equipo 1">
      <NombreEquipo> Monterey </NombreEquipo>
      <Puntuacion> 0 </Puntuacion>
      <estadisticas>Desempeño</estadisticas>
  </equipos>
    <equipos tipo="equipo 2">
        <NombreEquipo> Atletico San Luis </NombreEquipo>
        <Puntuacion> 2 </Puntuacion>
        <estadisticas>Desempeño</estadisticas>
    </equipos>

</Partido>
</Liga>
